### ISSUE TITLE
Event listener is not compatible with TYPO3 cms-form extension

### ISSUE THREAD

**Issue by MarcoHaase** [in2code-de/powermail#909]
event.listener 'form-framework/modify-data-structure' in `Services.yaml` of Form and Powermail 

Both Extensions use same identifier with different classes

```
  TYPO3\CMS\Form\EventListener\DataStructureIdentifierListener:
    tags:
      - name: event.listener
        identifier: 'form-framework/modify-data-structure'
        method: 'modifyDataStructure'
```

```
  In2code\Powermail\EventListener\FlexFormParsingModifyEventListener:
    tags:
      - name: 'event.listener'
        identifier: 'form-framework/modify-data-structure'
        method: 'modifyDataStructure'
```

this leads to the fact that the form definitions can no longer be selected in cms-form because none are available in the select box.

**Comment by MarcoHaase** [comment]
active event.listener:
<img width="859" alt="image" src="https://github.com/einpraegsam/powermail/assets/86526555/050ca75a-ab43-4e0d-a48d-c398b016e16d">

<img width="413" alt="image" src="https://github.com/einpraegsam/powermail/assets/86526555/d89f95e1-9578-4f74-8a50-0f3bf2f12a50">

inactive event.listener:
<img width="477" alt="image" src="https://github.com/einpraegsam/powermail/assets/86526555/175118f1-b9f9-42fd-b4f3-39df9cb67ee6">

<img width="401" alt="image" src="https://github.com/einpraegsam/powermail/assets/86526555/1c534265-e4f9-4204-8ae5-2d3136c403d9">

**Comment by MarcoHaase** [comment]
workarround:

TypoScript options of root:

set the order so that the sitepackage's `Service.yaml` is loaded last:

e.g.
1. Form
2. Powermail
3. MySitepackage

add to files to your sitepackage:

Vendor/MySitepackage/Classes/EventListener/PowermailFormEventListener.php:
```
<?php

declare(strict_types=1);

namespace Vendor\MySitepackage\EventListener;

use TYPO3\CMS\Core\Configuration\Event\AfterFlexFormDataStructureParsedEvent;
use In2code\Powermail\EventListener\FlexFormParsingModifyEventListener as Powermail;
use TYPO3\CMS\Form\EventListener\DataStructureIdentifierListener as Form;
use TYPO3\CMS\Core\Utility\GeneralUtility;

final class PowermailFormEventListener
{
    public function modifyDataStructure(AfterFlexFormDataStructureParsedEvent $event): void
    {
        $identifier = $event->getIdentifier();
       
        if (($identifier['dataStructureKey'] ?? '') === '*,powermail_pi1') {
            $PowermailEventListener = GeneralUtility::makeInstance(Powermail::class);
            $PowermailEventListener->modifyDataStructure($event);
        }
        if (($identifier['dataStructureKey'] ?? '') === '*,form_formframework') {
            $FormEventListener = GeneralUtility::makeInstance(Form::class);
            $FormEventListener->modifyDataStructure($event);
        }
    }
}
```

Vendor/MySitepackage/Configuration/Services.yaml:
```
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Vendor\MySitepackage\:
        resource: "../Classes/*"

    Vendor\MySitepackage\EventListener\PowermailFormEventListener:
        tags:
            - name: "event.listener"
              identifier: "form-framework/modify-data-structure"
              method: "modifyDataStructure"
              after: "form-framework/modify-data-structure"
```
